name: Publish PowerShell Module(s)
description: Publishes PowerShell module(s) to the PowerShell Gallery
inputs:
  ApiKey:
    description: The API Key for pushing to PowerShell Gallery
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.ApiKey }}
